/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package dev.cyberstamp.sigmund.resolver.generator;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Predicate;
import org.eclipse.aether.artifact.Artifact;
import org.eclipse.aether.spi.artifact.generator.ArtifactGenerator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

final class SigmundSignatureArtifactGenerator implements ArtifactGenerator {
    private final Logger logger = LoggerFactory.getLogger(getClass());
    private final List<Artifact> artifacts;
    private final Predicate<Artifact> signableArtifactPredicate;
    private final AtomicBoolean closed;

    SigmundSignatureArtifactGenerator(Collection<Artifact> artifacts, Predicate<Artifact> signableArtifactPredicate) {
        this.artifacts = new ArrayList<>(artifacts);
        this.signableArtifactPredicate = signableArtifactPredicate;
        this.closed = new AtomicBoolean(false);
    }

    @Override
    public String generatorId() {
        return SigmundSignatureArtifactGeneratorFactory.NAME;
    }

    @Override
    public synchronized Collection<? extends Artifact> generate(Collection<? extends Artifact> generatedArtifacts) {
        artifacts.addAll(generatedArtifacts); // add generated by other generators (before this)

        // back out if PGP signatures found among artifacts; user uses m-gpg-p?
        if (artifacts.stream().anyMatch(a -> a.getExtension().endsWith(".asc"))) {
            logger.debug("GPG signatures are present among artifacts, bailing out");
            return Collections.emptyList();
        }

        // sign relevant artifacts
        ArrayList<Artifact> result = new ArrayList<>();
        for (Artifact artifact : artifacts) {
            if (signableArtifactPredicate.test(artifact)) {
                // sign and add signature artifact (w/ file set) to list
                //   result.add(new SubArtifact(
                //     artifact,
                //     artifact.getClassifier(),
                //     artifact.getExtension() + ARTIFACT_EXTENSION,
                //     signatureTempFile.toFile()));
            }
        }
        logger.debug("Signed {} artifacts", result.size());
        return result;
    }

    @Override
    public void close() {
        if (closed.compareAndSet(false, true)) {
            // close
        }
    }
}
